config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/about', to: 'pages#about'
  get '/talks', to: 'talks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/talk.rb
class Talk < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = "Webpacker"
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    @talks = Talk.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactTrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
          <div class="container">
            <%= link_to "React Track", root_path, id: "logo" %>
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",   root_path %></li>
                <li><%= link_to "Talks",   talks_path %></li>
                <li><%= link_to "About",   about_path %></li>
              </ul>
            </nav>
          </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is a static about page.</h1>

app/views/pages/index.html.erb
<%= javascript_pack_tag 'hello' %>
<h1>The text below is generated by a React component</h1>
<%= react_component('Hello', name: @name) %>

app/views/talks/index.html.erb
<h1>The list of talks below is generated by ERB</h1>

<ul class="talks">
  <% @talks.each do |talk| %>
    <li>
      <%= talk.name %>
    </li>
  <% end %>
</ul>

<%= javascript_pack_tag 'talks' %>
<h1>The text below is generated by a React component</h1>
<%= react_component('Talks', talks: @talks) %>